replicaCount: 3

namespace: www-cso

image:
  repository: chrissearle/www_cso
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: [
  name: regcred
]

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}
selectorLabels: {}

deployment:
  port: 3000

service:
  type: ClusterIP
  port: 11110

livenessProbe:
  httpGet:
    path: /
    port: 3000

readinessProbe:
  httpGet:
    path: /
    port: 3000