---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
  namespace: www-cso
spec:
  encryptedData:
    .dockerconfigjson: AgA2z8TxiAtRrNxIz6yjYpT5P7zuIOzn+S+rUSSaO654B1BwK88/ych/24e9O8gVFgVtwlYMYCeUjxI1M0iVuc7aimGiHT2HkUOvOPqfzswEn+sxoVIPwnpXVZNrnihuiR4a5N1+a6XieMx5L4bWGq31+JcC0n+OXOaHp/BbUBGpw1JKtP2+LPeDH+gJBMX3myeX4EoXiGBMNK6u9prOf8aF+faFURNLOM1IknCk0vY9tm2bvMgg/EU2fG1Ufu9N9PCVSAKb1f0i17mHR8oi9N6Vc4aE3INjBGYYN5pa+w/GrBJi/Q/OmZbMoHIhYB3O81SaPiychPRlrxt45z/hU2uTjb+884MNM+lwDct06S+x0WKV3KstOBLpf7wfLccZ1a54+3yTinpQHkE8Lr1nrCF/PGZTsQYo/CS4Pxqg4eepldjKXzZ0m9TQV8oLYqq8XrbWWWVNGgFM4kEAGnqX1Ii2B89X/ecFhAAnH7TEw2Eo49pf7ghLMWprHeLoq5FClP0042GZGeq+uXkY1jbwODXXjLZQKTVDe4iIxb6rD/7WNcSXubLrByfvNLizVDt2pMSkyzuSynjkw3M4AXB3mhpBuclbSqyW2vfWCN2Omvq/nYr5X/BpVEsWRMsGtqPqUi1I/26qvc2jzYQ2Ybl/5QoMQIoHnwmKc+Jt2fT/ws9LFlHbMrDy+kGNnZ197Z6r4nLVXWYQmnJ8oaGqO5HJ0M4lKxpNVASRDSnP6Js/zQbgkkBwyVmVay5Be6uYLLZPQD0x7oVaQX1mT5zFZRzR03HHZXLkr0/OPgArCkWgKQnMmvSslG8XJz4NaWPox0bNAeurjfWvUn0x4MgbG39dv1a2eQwKQzhujmhFy2HaamtBt5nkcaJf/2E=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
      namespace: www-cso
    type: kubernetes.io/dockerconfigjson
